services:
  db:
    image: mysql:latest
    container_name: daily_diet_db
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'daily_diet'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /home/andersonrosa/Documentos/Projects/Daily-Diet-API/mysql_daily_diet:/var/lib/mysql